[package]
name = "git-changelog"
version = "0.1.0"
authors = ["Rene Richter <richterrettich@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.8"
regex = "1"
lazy_static = "1.3.0"
crossbeam = "0.7"